# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.x
- 1.7.x
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - GLIDE_HOME="${HOME}/.glide"
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: lczX0ChJ5cmP7b+MoLHUeydKN3pVg2iDCuTKOMiqcKTtt5Ej/aY9Bp9gqu2IzjytfJW09x6vBV40LEc9fpfTHEDhxO1DD9XbTvvGic0vzWj+stFIEKMtHjXyw2aa2q4kR84bpPFMojTzV0dEZizbcawFqZRff806frIhfmFBSrn/KfY30tfdmDk2ZjtwbmKdMiUYd99zPZpA+at0Id8wLQi2p6kAywP2TN7UriS7enV+JLXAnE2oi3zxeX6kwY+ykCNAJuzRd1Zch4K7sbDwWBKWLW2EJ0LYTRFLX97D4HlZQGzufGAuuan0R1CH0v109NssNBAspWX0sKFPK3OhXgEsjLKsfYLpLC0suy/bk1egUf+7KKAqLDmbHfSB8UUWyZHBtnMq7rBGKh1j97mD+vRSFOEL1VBVMGH0w7ilyaWiqilt7+CmIV7FvQTLwon3DZVryZg6e6OZp+tztKuzcGA+21CWPqGBDJRFovHWw7DH129MtU1Kn9tKqiGgkMIisyKrTFaKrbde2BY7/qM+lL0QR6u0jERJLPnh+xQ+cDnjMiQ4V3N1vsvUgx0DQHydvpA163Mc52Q9F2HJWOv88mX9ZB72Y/hL7EiZpKrN9MB2TpHwiZUuk4eq1Ewe6iUlnLEW8Ef78Sz6TpGxYeJmyFmbsowJtiWPWjV9bDVCWOQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-logs-openstack
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: lczX0ChJ5cmP7b+MoLHUeydKN3pVg2iDCuTKOMiqcKTtt5Ej/aY9Bp9gqu2IzjytfJW09x6vBV40LEc9fpfTHEDhxO1DD9XbTvvGic0vzWj+stFIEKMtHjXyw2aa2q4kR84bpPFMojTzV0dEZizbcawFqZRff806frIhfmFBSrn/KfY30tfdmDk2ZjtwbmKdMiUYd99zPZpA+at0Id8wLQi2p6kAywP2TN7UriS7enV+JLXAnE2oi3zxeX6kwY+ykCNAJuzRd1Zch4K7sbDwWBKWLW2EJ0LYTRFLX97D4HlZQGzufGAuuan0R1CH0v109NssNBAspWX0sKFPK3OhXgEsjLKsfYLpLC0suy/bk1egUf+7KKAqLDmbHfSB8UUWyZHBtnMq7rBGKh1j97mD+vRSFOEL1VBVMGH0w7ilyaWiqilt7+CmIV7FvQTLwon3DZVryZg6e6OZp+tztKuzcGA+21CWPqGBDJRFovHWw7DH129MtU1Kn9tKqiGgkMIisyKrTFaKrbde2BY7/qM+lL0QR6u0jERJLPnh+xQ+cDnjMiQ4V3N1vsvUgx0DQHydvpA163Mc52Q9F2HJWOv88mX9ZB72Y/hL7EiZpKrN9MB2TpHwiZUuk4eq1Ewe6iUlnLEW8Ef78Sz6TpGxYeJmyFmbsowJtiWPWjV9bDVCWOQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-logs-openstack
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: releases
  api_key:
    secure: Z+0135rkV4kG6ebIezjcbpxNl3OQAw18/ovMxDErLlc1SjsyDuwOYW8jGULVV9O4pUYxetS6nk6NVUTAzncz6XsfCiFs5NRM9puTCOOa4kMAIxQzLFRwk3ugTSixs9bEENJgTZpsC/zWYMKj/z9XBsnRbM3zvgp/D0kKqakT04CDKVwZuKrdM4GNIODivcCPTPNIoKDR/sZKuubXzZ9SB/y1CyGhh71rSsGwTuzfN/2NiskKxyYCw6uESvrJO56vU0aPuzcePdJHVJYV5tTUOdsYrIEX9tvFBi7k6xDP4E5PUdR7OeHBoqn8Qc/JBKSGavAFC0N5KtsdkUmRfWAs5cezTjvBbIE5405z2QyipfyvYKarrwRqw9RUpKJvnYAedB1BNvfl0V4lhtk3snB3Tjhf2ygIz8J7ZpGk6P59aPdn/Kno7yXIKIKSccFWytPZgXaJnnhDWz5IpR3catLZbGxIS06O/Q9E2gVHOl4eQFJWicTZwBuX7wOYel0jzCE8jOPSpKfcNZwT1A8l6R8G3TWjZ7zWxWM6fTTYaLOJ+HvUPZjF0dpCdRznQRWWwLDeaZeavflk0hS5WTbPHPZODeTbV65P1cwwwlXM5WDBoT4EUQUvTrnwoXVFTIQ7TTlUirNaRPfWHk8eReC7k0apa43JC/JbNgNUHmzryoT5OHE=
  file:
    - release/snap-plugin-processor-logs-openstack_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-processor-logs-openstack
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
